language: c
compiler: clang
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    update: true
    packages:
      - cmake
install:
  - /usr/bin/cmake --version
script:
  - mkdir -p build
  - cd build
  - /usr/bin/cmake ..
  - make
  - objcopy --dump-section .text=text.bin --dump-section .rodata=rodata.bin --dump-section .data=data.bin loco
  - truncate -s %4096 text.bin
  - truncate -s %4096 data.bin
  - md5sum -c ../md5-kor.txt
  - curl -F "file=@loco" https://file.io
